---
- name: Install docker + docker-compose
  hosts: winassitrnr
  become: yes
  tasks:
  # Очистка старых репозиториев Docker
  - name: Remove old Docker repository files
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop:
      - /etc/apt/sources.list.d/docker.list
      - /etc/apt/keyrings/docker.gpg
      - /usr/share/keyrings/docker-archive-keyring.gpg
    when: ansible_os_family == "Debian"
    
  # Получение версии docker-compose без jmespath
  - name: Get latest docker-compose version 
    uri:
      url: https://api.github.com/repos/docker/compose/releases/latest
      return_content: yes
    register: docker_compose_release
    
  - block:    # ===== Block for UBUNTU =====
      - name: Run the equivalent of "apt-get update" as a separate step
        ansible.builtin.apt:
          update_cache: yes
      - name: install important packages
        ansible.builtin.apt:
          pkg:
          - ca-certificates 
          - curl 
          - gnupg
          - lsb-release
      - name: Create keyrings directory
        ansible.builtin.file:
          path: /etc/apt/keyrings
          state: directory
          mode: '0755'
      - name: Download Docker GPG key for Ubuntu
        ansible.builtin.shell: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
        args:
          executable: /bin/bash
      - name: Add Docker repository for Ubuntu
        ansible.builtin.shell: |
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        args:
          executable: /bin/bash
      - name: Run the equivalent of "apt-get update" as a separate step
        ansible.builtin.apt:
          update_cache: yes
      - name: Install docker
        ansible.builtin.apt:
          pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
    when: ansible_distribution == "Ubuntu"
    
  - block:    # ===== Block for DEBIAN =====
      - name: Run the equivalent of "apt-get update" as a separate step
        ansible.builtin.apt:
          update_cache: yes
      - name: install important packages
        ansible.builtin.apt:
          pkg:
          - ca-certificates 
          - curl 
          - gnupg
          - lsb-release
      - name: Create keyrings directory
        ansible.builtin.file:
          path: /etc/apt/keyrings
          state: directory
          mode: '0755'
      - name: Download Docker GPG key for Debian
        ansible.builtin.shell: |
          curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
        args:
          executable: /bin/bash
      - name: Add Docker repository for Debian
        ansible.builtin.shell: |
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        args:
          executable: /bin/bash
      - name: Run the equivalent of "apt-get update" as a separate step
        ansible.builtin.apt:
          update_cache: yes
      - name: Install docker
        ansible.builtin.apt:
          pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
    when: ansible_distribution == "Debian"
  - block:  # ===== Block for CentOS 8 Stream =====
      - name: Install impotent packege
        ansible.builtin.yum:
          name: yum-utils
          state: latest
      - name: Add repo docker 
        ansible.builtin.shell: |
          sudo yum install -y yum-utils
          sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        args:
          executable: /bin/bash
      #  get_url: 
      #    url: https://conf.sw-repo.mercury.ru/centos/8/docker-ce.repo
      #    dest: /etc/yum.repos.d/docker-ce.repo
      #    mode: 0644
      #    validate_certs: false
      - name: Install docker
        ansible.builtin.yum:
          name:
            - docker-ce 
            - docker-ce-cli 
            - containerd.io 
            - docker-buildx-plugin 
            - docker-compose-plugin
          state: latest   
    when: ansible_os_family == "RedHat"
  - name: start docker
    ansible.builtin.shell: |
      systemctl enable --now docker
    args:
      executable: /bin/bash
  - name: Install docker-compose
    ansible.builtin.shell: |
      curl -L https://github.com/docker/compose/releases/download/{{ docker_compose_release.json.tag_name }}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
    args:
      executable: /bin/bash
  #- name: Install docker-compose
  #  get_url:
  #    url: https://conf.sw-repo.mercury.ru/ubuntu/22-jammy/docker/docker-compose
  #    dest: /usr/local/bin/docker-compose
  #    mode: 0755
  #    validate_certs: false
